// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// varma_acf
Rcpp::List varma_acf(arma::cube ar, arma::cube ma, arma::mat cov_mat, int max_lag);
RcppExport SEXP _varma_varma_acf(SEXP arSEXP, SEXP maSEXP, SEXP cov_matSEXP, SEXP max_lagSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube >::type ar(arSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type ma(maSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type cov_mat(cov_matSEXP);
    Rcpp::traits::input_parameter< int >::type max_lag(max_lagSEXP);
    rcpp_result_gen = Rcpp::wrap(varma_acf(ar, ma, cov_mat, max_lag));
    return rcpp_result_gen;
END_RCPP
}
// varma_residuals
arma::mat varma_residuals(const arma::mat& Y, const arma::cube& Phi, const arma::cube& Theta, const arma::vec& intercept);
RcppExport SEXP _varma_varma_residuals(SEXP YSEXP, SEXP PhiSEXP, SEXP ThetaSEXP, SEXP interceptSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type Phi(PhiSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type Theta(ThetaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type intercept(interceptSEXP);
    rcpp_result_gen = Rcpp::wrap(varma_residuals(Y, Phi, Theta, intercept));
    return rcpp_result_gen;
END_RCPP
}
// irf_varma_rcpp
arma::cube irf_varma_rcpp(const arma::cube& A_cube, const arma::cube& M_cube, const arma::mat& P, int horizon);
RcppExport SEXP _varma_irf_varma_rcpp(SEXP A_cubeSEXP, SEXP M_cubeSEXP, SEXP PSEXP, SEXP horizonSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type A_cube(A_cubeSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type M_cube(M_cubeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type P(PSEXP);
    Rcpp::traits::input_parameter< int >::type horizon(horizonSEXP);
    rcpp_result_gen = Rcpp::wrap(irf_varma_rcpp(A_cube, M_cube, P, horizon));
    return rcpp_result_gen;
END_RCPP
}
// sim_varma_rcpp
arma::mat sim_varma_rcpp(const arma::cube& A, const arma::cube& M, const arma::mat& eps);
RcppExport SEXP _varma_sim_varma_rcpp(SEXP ASEXP, SEXP MSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(sim_varma_rcpp(A, M, eps));
    return rcpp_result_gen;
END_RCPP
}
// solve_dlyap_iter
arma::mat solve_dlyap_iter(const arma::sp_mat& T, const arma::mat& C, int max_iter, double tol);
RcppExport SEXP _varma_solve_dlyap_iter(SEXP TSEXP, SEXP CSEXP, SEXP max_iterSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type T(TSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type C(CSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(solve_dlyap_iter(T, C, max_iter, tol));
    return rcpp_result_gen;
END_RCPP
}
// kalmanLogLik
double kalmanLogLik(const arma::sp_mat& T, const arma::sp_mat& R, const arma::mat& Q, arma::mat& a1, arma::mat& P1, const arma::mat& Yt, const bool update_state);
RcppExport SEXP _varma_kalmanLogLik(SEXP TSEXP, SEXP RSEXP, SEXP QSEXP, SEXP a1SEXP, SEXP P1SEXP, SEXP YtSEXP, SEXP update_stateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type T(TSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Q(QSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type a1(a1SEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type P1(P1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Yt(YtSEXP);
    Rcpp::traits::input_parameter< const bool >::type update_state(update_stateSEXP);
    rcpp_result_gen = Rcpp::wrap(kalmanLogLik(T, R, Q, a1, P1, Yt, update_state));
    return rcpp_result_gen;
END_RCPP
}
// kalman
double kalman(const arma::sp_mat& T, const arma::sp_mat& R, const arma::mat& Q, arma::mat& at, arma::Cube<double>& Pt, const arma::mat& Yt, arma::mat& v, arma::Cube<double>& F, const bool update_state);
RcppExport SEXP _varma_kalman(SEXP TSEXP, SEXP RSEXP, SEXP QSEXP, SEXP atSEXP, SEXP PtSEXP, SEXP YtSEXP, SEXP vSEXP, SEXP FSEXP, SEXP update_stateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type T(TSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Q(QSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type at(atSEXP);
    Rcpp::traits::input_parameter< arma::Cube<double>& >::type Pt(PtSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Yt(YtSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type v(vSEXP);
    Rcpp::traits::input_parameter< arma::Cube<double>& >::type F(FSEXP);
    Rcpp::traits::input_parameter< const bool >::type update_state(update_stateSEXP);
    rcpp_result_gen = Rcpp::wrap(kalman(T, R, Q, at, Pt, Yt, v, F, update_state));
    return rcpp_result_gen;
END_RCPP
}
// sur_cpp
arma::vec sur_cpp(const Rcpp::List& X_list, const Rcpp::List& y_list, const arma::mat& sigma);
RcppExport SEXP _varma_sur_cpp(SEXP X_listSEXP, SEXP y_listSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type X_list(X_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type y_list(y_listSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(sur_cpp(X_list, y_list, sigma));
    return rcpp_result_gen;
END_RCPP
}
// var_filter
arma::mat var_filter(const arma::mat& X, const arma::cube& A, Rcpp::Nullable<arma::mat> Y0);
RcppExport SEXP _varma_var_filter(SEXP XSEXP, SEXP ASEXP, SEXP Y0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type A(ASEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::mat> >::type Y0(Y0SEXP);
    rcpp_result_gen = Rcpp::wrap(var_filter(X, A, Y0));
    return rcpp_result_gen;
END_RCPP
}
// estimate_varma_gls_cpp
List estimate_varma_gls_cpp(arma::mat Y, arma::mat U, arma::mat SigmaU_inv, int p, int q, String type);
RcppExport SEXP _varma_estimate_varma_gls_cpp(SEXP YSEXP, SEXP USEXP, SEXP SigmaU_invSEXP, SEXP pSEXP, SEXP qSEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type U(USEXP);
    Rcpp::traits::input_parameter< arma::mat >::type SigmaU_inv(SigmaU_invSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    Rcpp::traits::input_parameter< String >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(estimate_varma_gls_cpp(Y, U, SigmaU_inv, p, q, type));
    return rcpp_result_gen;
END_RCPP
}
// autocov_gs_cpp
arma::cube autocov_gs_cpp(Rcpp::Nullable<arma::cube> ar_in, Rcpp::Nullable<arma::cube> ma_in, arma::mat cov, int max_lag);
RcppExport SEXP _varma_autocov_gs_cpp(SEXP ar_inSEXP, SEXP ma_inSEXP, SEXP covSEXP, SEXP max_lagSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::cube> >::type ar_in(ar_inSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::cube> >::type ma_in(ma_inSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type cov(covSEXP);
    Rcpp::traits::input_parameter< int >::type max_lag(max_lagSEXP);
    rcpp_result_gen = Rcpp::wrap(autocov_gs_cpp(ar_in, ma_in, cov, max_lag));
    return rcpp_result_gen;
END_RCPP
}
// autocov_mc_cpp
arma::cube autocov_mc_cpp(const arma::cube& ar, const arma::cube& ma, const arma::mat& cov, int maxlag);
RcppExport SEXP _varma_autocov_mc_cpp(SEXP arSEXP, SEXP maSEXP, SEXP covSEXP, SEXP maxlagSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type ar(arSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type ma(maSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type cov(covSEXP);
    Rcpp::traits::input_parameter< int >::type maxlag(maxlagSEXP);
    rcpp_result_gen = Rcpp::wrap(autocov_mc_cpp(ar, ma, cov, maxlag));
    return rcpp_result_gen;
END_RCPP
}
// autocov_an_cpp
arma::cube autocov_an_cpp(arma::cube phi, arma::cube theta, arma::mat cov, int maxlag);
RcppExport SEXP _varma_autocov_an_cpp(SEXP phiSEXP, SEXP thetaSEXP, SEXP covSEXP, SEXP maxlagSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type cov(covSEXP);
    Rcpp::traits::input_parameter< int >::type maxlag(maxlagSEXP);
    rcpp_result_gen = Rcpp::wrap(autocov_an_cpp(phi, theta, cov, maxlag));
    return rcpp_result_gen;
END_RCPP
}
// autocov_mi_cpp
arma::cube autocov_mi_cpp(Rcpp::Nullable<arma::cube> ar_in, Rcpp::Nullable<arma::cube> ma_in, arma::mat cov, int max_lag);
RcppExport SEXP _varma_autocov_mi_cpp(SEXP ar_inSEXP, SEXP ma_inSEXP, SEXP covSEXP, SEXP max_lagSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::cube> >::type ar_in(ar_inSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::cube> >::type ma_in(ma_inSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type cov(covSEXP);
    Rcpp::traits::input_parameter< int >::type max_lag(max_lagSEXP);
    rcpp_result_gen = Rcpp::wrap(autocov_mi_cpp(ar_in, ma_in, cov, max_lag));
    return rcpp_result_gen;
END_RCPP
}
// rby_optimization_step
List rby_optimization_step(arma::mat Y, arma::cube Phi_cube, arma::cube Theta_cube, int p, int q, bool intercept, arma::vec c_vec);
RcppExport SEXP _varma_rby_optimization_step(SEXP YSEXP, SEXP Phi_cubeSEXP, SEXP Theta_cubeSEXP, SEXP pSEXP, SEXP qSEXP, SEXP interceptSEXP, SEXP c_vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type Phi_cube(Phi_cubeSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type Theta_cube(Theta_cubeSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    Rcpp::traits::input_parameter< bool >::type intercept(interceptSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type c_vec(c_vecSEXP);
    rcpp_result_gen = Rcpp::wrap(rby_optimization_step(Y, Phi_cube, Theta_cube, p, q, intercept, c_vec));
    return rcpp_result_gen;
END_RCPP
}
// kronecker_indices_cpp
Rcpp::IntegerVector kronecker_indices_cpp(const arma::cube& Phi, const arma::cube& Theta, const double tol);
RcppExport SEXP _varma_kronecker_indices_cpp(SEXP PhiSEXP, SEXP ThetaSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type Phi(PhiSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type Theta(ThetaSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(kronecker_indices_cpp(Phi, Theta, tol));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_varma_varma_acf", (DL_FUNC) &_varma_varma_acf, 4},
    {"_varma_varma_residuals", (DL_FUNC) &_varma_varma_residuals, 4},
    {"_varma_irf_varma_rcpp", (DL_FUNC) &_varma_irf_varma_rcpp, 4},
    {"_varma_sim_varma_rcpp", (DL_FUNC) &_varma_sim_varma_rcpp, 3},
    {"_varma_solve_dlyap_iter", (DL_FUNC) &_varma_solve_dlyap_iter, 4},
    {"_varma_kalmanLogLik", (DL_FUNC) &_varma_kalmanLogLik, 7},
    {"_varma_kalman", (DL_FUNC) &_varma_kalman, 9},
    {"_varma_sur_cpp", (DL_FUNC) &_varma_sur_cpp, 3},
    {"_varma_var_filter", (DL_FUNC) &_varma_var_filter, 3},
    {"_varma_estimate_varma_gls_cpp", (DL_FUNC) &_varma_estimate_varma_gls_cpp, 6},
    {"_varma_autocov_gs_cpp", (DL_FUNC) &_varma_autocov_gs_cpp, 4},
    {"_varma_autocov_mc_cpp", (DL_FUNC) &_varma_autocov_mc_cpp, 4},
    {"_varma_autocov_an_cpp", (DL_FUNC) &_varma_autocov_an_cpp, 4},
    {"_varma_autocov_mi_cpp", (DL_FUNC) &_varma_autocov_mi_cpp, 4},
    {"_varma_rby_optimization_step", (DL_FUNC) &_varma_rby_optimization_step, 7},
    {"_varma_kronecker_indices_cpp", (DL_FUNC) &_varma_kronecker_indices_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_varma(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
