# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

varma_acf <- function(ar, ma, cov_mat, max_lag) {
    .Call(`_varma_varma_acf`, ar, ma, cov_mat, max_lag)
}

irf_varma_rcpp <- function(A_cube, M_cube, P, horizon) {
    .Call(`_varma_irf_varma_rcpp`, A_cube, M_cube, P, horizon)
}

sim_varma_rcpp <- function(A, M, eps) {
    .Call(`_varma_sim_varma_rcpp`, A, M, eps)
}

solve_riccati <- function(T, R, Q) {
    .Call(`_varma_solve_riccati`, T, R, Q)
}

solve_syl <- function(A, B, C) {
    .Call(`_varma_solve_syl`, A, B, C)
}

solve_dlyap_iter <- function(T, C, max_iter = 200L, tol = 1e-10) {
    .Call(`_varma_solve_dlyap_iter`, T, C, max_iter, tol)
}

kalmanLogLik <- function(T, R, Q, a1, P1, Yt, update_state = FALSE) {
    .Call(`_varma_kalmanLogLik`, T, R, Q, a1, P1, Yt, update_state)
}

kalman <- function(T, R, Q, at, Pt, Yt, v, F, update_state = FALSE) {
    .Call(`_varma_kalman`, T, R, Q, at, Pt, Yt, v, F, update_state)
}

sur_cpp <- function(X_list, y_list, sigma) {
    .Call(`_varma_sur_cpp`, X_list, y_list, sigma)
}

var_filter <- function(X, A, Y0 = NULL) {
    .Call(`_varma_var_filter`, X, A, Y0)
}

#' GLS estimation of VARMA using the diagonal MA or final MA form
#'
#' @param Y data matrix
#' @param U innovation matrix
#' @param SigmaU_inv inverse of the innovation covariance matrix
#' @param p order of VAR part
#' @param q order of VMA part
#' @param type a string with one of the two choices "diagonal", "final"
estimate_varma_gls_cpp <- function(Y, U, SigmaU_inv, p, q, type) {
    .Call(`_varma_estimate_varma_gls_cpp`, Y, U, SigmaU_inv, p, q, type)
}

#' Autocovariance function using Sbrana's formula
#'
#' @param ar_in a 3d-array with the p AR coefficient matrices
#' @param ma_in a 3d-array with the q MA coefficient matrices
#' @param cov covariance matrix of the innovations
#' @param max_lag non-negative integer with max lag of the autocovariance function
#'
#' @returns A 3d array with the max_lag+1 autocovariance matrices
autocov_gs_cpp <- function(ar_in, ma_in, cov, max_lag) {
    .Call(`_varma_autocov_gs_cpp`, ar_in, ma_in, cov, max_lag)
}

autocov_mc_cpp <- function(ar, ma, cov, maxlag = 10L) {
    .Call(`_varma_autocov_mc_cpp`, ar, ma, cov, maxlag)
}

autocov_an_cpp <- function(phi, theta, cov, maxlag) {
    .Call(`_varma_autocov_an_cpp`, phi, theta, cov, maxlag)
}

#' Compute theoretical autocovariance matrices for a VARMA(p,q) process
#' using the method of Mittnik (1990). Identical call convention to
#' \code{autocov_gs_cpp}: \code{ma_in} holds B_1,...,B_q only; B_0 = I is implicit.
#'
#' @param ar_in   3D array (m x m x p) of AR coefficients A_1,...,A_p, or NULL.
#' @param ma_in   3D array (m x m x q) of MA coefficients B_1,...,B_q, or NULL.
#' @param cov     Innovation covariance matrix Sigma (m x m).
#' @param max_lag Number of lags to return beyond lag 0.
#' @return 3D array (m x m x (max_lag+1)); slice k+1 (1-based in R) is Gamma_k.
#'
#' @examples
#' \dontrun{
#' sourceCpp("mittnik1990_acov.cpp")
#'
#' # Univariate AR(1): Gamma_k = phi^k / (1 - phi^2)
#' G <- varma_acov(array(0.7, c(1,1,1)), NULL, matrix(1), max_lag = 5)
#'
#' # Bivariate VARMA(1,1)
#' m  <- 2
#' A1 <- matrix(c(0.4, 0.2, 0.1, 0.3), m, m)
#' B1 <- matrix(c(0.2, 0.1, 0.0, 0.2), m, m)
#' G  <- varma_acov(array(A1, c(m,m,1)), array(B1, c(m,m,1)), diag(m), max_lag = 8)
#' G[,,1]  # Gamma_0 (symmetric)
#' G[,,2]  # Gamma_1
#' }
autocov_mi_cpp <- function(ar_in, ma_in, cov, max_lag = 0L) {
    .Call(`_varma_autocov_mi_cpp`, ar_in, ma_in, cov, max_lag)
}

rby_optimization_step <- function(Y, Phi_cube, Theta_cube, p, q, intercept, c_vec) {
    .Call(`_varma_rby_optimization_step`, Y, Phi_cube, Theta_cube, p, q, intercept, c_vec)
}

