# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

varma_acf <- function(ar, ma, cov_mat, max_lag) {
    .Call(`_varma_varma_acf`, ar, ma, cov_mat, max_lag)
}

#' VARMA residuals
#'
#' Iterates the VARMA(p, q) recursion forward to produce one-step-ahead
#' residuals.  The first \code{max(p, q)} rows of the output are zero
#' (pre-sample); valid residuals begin at row \code{max(p, q) + 1} (1-indexed).
#' The AR part conditions on the observed \code{Y[1:p, ]}; pre-sample errors
#' used by the MA part are initialised to zero.
#'
#' @param Y         \eqn{n \times m} matrix of observations (rows = time points).
#' @param Phi       \eqn{m \times m \times p} cube of VAR coefficient matrices.
#'                  Pass \code{array(0, c(m, m, 0))} when \code{p = 0}.
#' @param Theta     \eqn{m \times m \times q} cube of VMA coefficient matrices.
#'                  Pass \code{array(0, c(m, m, 0))} when \code{q = 0}.
#' @param intercept \eqn{m}-vector of intercepts. Pass \code{numeric(0)} to
#'                  omit the intercept.
#' @return \eqn{n \times m} matrix of residuals.
varma_residuals <- function(Y, Phi, Theta, intercept) {
    .Call(`_varma_varma_residuals`, Y, Phi, Theta, intercept)
}

irf_varma_rcpp <- function(A_cube, M_cube, P, horizon) {
    .Call(`_varma_irf_varma_rcpp`, A_cube, M_cube, P, horizon)
}

sim_varma_rcpp <- function(A, M, eps) {
    .Call(`_varma_sim_varma_rcpp`, A, M, eps)
}

solve_dlyap_iter <- function(T, C, max_iter = 200L, tol = 1e-10) {
    .Call(`_varma_solve_dlyap_iter`, T, C, max_iter, tol)
}

kalmanLogLik <- function(T, R, Q, a1, P1, Yt, update_state = FALSE, ss_tol = 1e-8) {
    .Call(`_varma_kalmanLogLik`, T, R, Q, a1, P1, Yt, update_state, ss_tol)
}

kalman <- function(T, R, Q, at, Pt, Yt, v, F, update_state = FALSE) {
    .Call(`_varma_kalman`, T, R, Q, at, Pt, Yt, v, F, update_state)
}

sur_cpp <- function(X_list, y_list, sigma) {
    .Call(`_varma_sur_cpp`, X_list, y_list, sigma)
}

var_filter <- function(X, A, Y0 = NULL) {
    .Call(`_varma_var_filter`, X, A, Y0)
}

#' GLS estimation of VARMA using the diagonal MA or final MA form
#'
#' @param Y data matrix
#' @param U innovation matrix
#' @param SigmaU_inv inverse of the innovation covariance matrix
#' @param p order of VAR part
#' @param q order of VMA part
#' @param type a string with one of the two choices "diagonal", "final"
estimate_varma_gls_cpp <- function(Y, U, SigmaU_inv, p, q, type) {
    .Call(`_varma_estimate_varma_gls_cpp`, Y, U, SigmaU_inv, p, q, type)
}

#' Autocovariance function using Sbrana's formula
#'
#' @param ar_in a 3d-array with the p AR coefficient matrices
#' @param ma_in a 3d-array with the q MA coefficient matrices
#' @param cov covariance matrix of the innovations
#' @param max_lag non-negative integer with max lag of the autocovariance function
#'
#' @returns A 3d array with the max_lag+1 autocovariance matrices
autocov_gs_cpp <- function(ar_in, ma_in, cov, max_lag) {
    .Call(`_varma_autocov_gs_cpp`, ar_in, ma_in, cov, max_lag)
}

autocov_mc_cpp <- function(ar, ma, cov, maxlag = 10L) {
    .Call(`_varma_autocov_mc_cpp`, ar, ma, cov, maxlag)
}

autocov_an_cpp <- function(phi, theta, cov, maxlag) {
    .Call(`_varma_autocov_an_cpp`, phi, theta, cov, maxlag)
}

#' Compute theoretical autocovariance matrices for a VARMA(p,q) process
#' using the method of Mittnik (1990). Identical call convention to
#' \code{autocov_gs_cpp}: \code{ma_in} holds B_1,...,B_q only; B_0 = I is implicit.
#'
#' @param ar_in   3D array (m x m x p) of AR coefficients A_1,...,A_p, or NULL.
#' @param ma_in   3D array (m x m x q) of MA coefficients B_1,...,B_q, or NULL.
#' @param cov     Innovation covariance matrix Sigma (m x m).
#' @param max_lag Number of lags to return beyond lag 0.
#' @return 3D array (m x m x (max_lag+1)); slice k+1 (1-based in R) is Gamma_k.
#'
#' @examples
#' \dontrun{
#' sourceCpp("mittnik1990_acov.cpp")
#'
#' # Univariate AR(1): Gamma_k = phi^k / (1 - phi^2)
#' G <- varma_acov(array(0.7, c(1,1,1)), NULL, matrix(1), max_lag = 5)
#'
#' # Bivariate VARMA(1,1)
#' m  <- 2
#' A1 <- matrix(c(0.4, 0.2, 0.1, 0.3), m, m)
#' B1 <- matrix(c(0.2, 0.1, 0.0, 0.2), m, m)
#' G  <- varma_acov(array(A1, c(m,m,1)), array(B1, c(m,m,1)), diag(m), max_lag = 8)
#' G[,,1]  # Gamma_0 (symmetric)
#' G[,,2]  # Gamma_1
#' }
autocov_mi_cpp <- function(ar_in, ma_in, cov, max_lag = 0L) {
    .Call(`_varma_autocov_mi_cpp`, ar_in, ma_in, cov, max_lag)
}

rby_optimization_step <- function(Y, Phi_cube, Theta_cube, p, q, intercept, c_vec) {
    .Call(`_varma_rby_optimization_step`, Y, Phi_cube, Theta_cube, p, q, intercept, c_vec)
}

#' Kronecker indices for the VARMA echelon form
#'
#' Determines the Kronecker indices from the VARMA transfer function
#' \eqn{\Phi(z)^{-1}\Theta(z)} via the rank profile of the block Hankel
#' matrix of impulse-response coefficients.  The identity
#' \eqn{\mathrm{rank}(H_s) = \sum_k \min(\kappa_k, s)} implies
#' \eqn{\Delta_s = \mathrm{rank}(H_s) - \mathrm{rank}(H_{s-1}) = \#\{k : \kappa_k \ge s\}},
#' so the Kronecker indices are the conjugate partition of
#' \eqn{(\Delta_1, \Delta_2, \ldots)}.
#'
#' @param Phi   \eqn{m \times m \times p} cube of VAR coefficients.
#'              Pass a zero-slice cube (\code{array(0, c(m, m, 0))}) when
#'              \code{p = 0}.
#' @param Theta \eqn{m \times m \times q} cube of VMA coefficients.
#'              Pass a zero-slice cube when \code{q = 0}.
#' @param tol   Relative singular-value threshold for numerical rank
#'              (default \code{1e-8}).
#' @return Integer vector of length \code{m} with Kronecker indices sorted
#'         in non-increasing order.
kronecker_indices_cpp <- function(Phi, Theta, tol = 1e-8) {
    .Call(`_varma_kronecker_indices_cpp`, Phi, Theta, tol)
}

